eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: mcsv-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: estudiantes
          uri: http://localhost:8090
          predicates: 
            - Path=/api/v1/estudiantes/**
        - id: cursos
          uri: http://localhost:9090
          predicates: 
            - Path=/api/v1/cursos/**
